name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Only run when changes are made on main
    paths-ignore:
      - 'README.md' # Exclude changes to the root README.md
      - '.github/workflows/**' # Exclude changes to any GitHub Action workflows
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install CairoSVG mkdocs-material mkdocs-minify-plugin mkdocs-redirects mkdocs-rss-plugin ffc-mkdocs-video --no-cache-dir

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          python -m mkdocs gh-deploy --config-file mkdocs.yml --remote-branch gh-pages